.TH REDIS-SERVER 1 "November 27, 2015"
.SH NAME
discnt-server \- Distributed counters
.SH SYNOPSIS
.B discnt-server
.RI configfile
.SH DESCRIPTION
Discnt provides in memory distributed eventually consistent counters.
.PP
.SH OPTIONS
.IP "configfile"
Read options from specified configuration file.
.SH AUTHOR
\fBdiscnt-server\fP was written by Erik Dubbelboer.
.PP
