adlist.o: adlist.c adlist.h zmalloc.h
ae.o: ae.c ae.h zmalloc.h config.h ae_kqueue.c
ae_kqueue.o: ae_kqueue.c
ae_select.o: ae_select.c
anet.o: anet.c fmacros.h anet.h
bio.o: bio.c discnt.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  skiplist.h zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  bio.h
blocked.o: blocked.c discnt.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h skiplist.h zmalloc.h anet.h version.h util.h latency.h \
  sparkline.h counter.h
cluster.o: cluster.c discnt.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h skiplist.h zmalloc.h anet.h version.h util.h latency.h \
  sparkline.h cluster.h counter.h endianconv.h
config.o: config.c discnt.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  skiplist.h zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  cluster.h counter.h
crc16.o: crc16.c discnt.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  skiplist.h zmalloc.h anet.h version.h util.h latency.h sparkline.h
crc64.o: crc64.c
debug.o: debug.c discnt.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  skiplist.h zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  sha1.h crc64.h counter.h bio.h
dict.o: dict.c fmacros.h dict.h zmalloc.h discntassert.h
discnt-cli.o: discnt-cli.c fmacros.h version.h ../deps/hiredis/hiredis.h \
  sds.h zmalloc.h ../deps/linenoise/linenoise.h help.h anet.h ae.h
discnt.o: discnt.c discnt.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  skiplist.h zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  cluster.h counter.h bio.h asciilogo.h
endianconv.o: endianconv.c
counter.o: counter.c discnt.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  skiplist.h zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  cluster.h counter.h sha1.h endianconv.h
latency.o: latency.c discnt.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h skiplist.h zmalloc.h anet.h version.h util.h latency.h \
  sparkline.h
lzf_c.o: lzf_c.c lzfP.h
lzf_d.o: lzf_d.c lzfP.h
memtest.o: memtest.c config.h
networking.o: networking.c discnt.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h skiplist.h zmalloc.h anet.h version.h util.h latency.h \
  sparkline.h
object.o: object.c discnt.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  skiplist.h zmalloc.h anet.h version.h util.h latency.h sparkline.h
release.o: release.c release.h version.h crc64.h
sds.o: sds.c sds.h zmalloc.h
setproctitle.o: setproctitle.c
sha1.o: sha1.c sha1.h config.h
skiplist.o: skiplist.c discnt.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h skiplist.h zmalloc.h anet.h version.h util.h latency.h \
  sparkline.h
sparkline.o: sparkline.c discnt.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h skiplist.h zmalloc.h anet.h version.h util.h latency.h \
  sparkline.h
syncio.o: syncio.c discnt.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  skiplist.h zmalloc.h anet.h version.h util.h latency.h sparkline.h
util.o: util.c fmacros.h util.h sds.h sha1.h
zmalloc.o: zmalloc.c config.h zmalloc.h
