adlist.o: adlist.c adlist.h zmalloc.h
ae.o: ae.c ae.h zmalloc.h config.h ae_kqueue.c
ae_kqueue.o: ae_kqueue.c
ae_select.o: ae_select.c
anet.o: anet.c fmacros.h anet.h
bio.o: bio.c server.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  bio.h
blocked.o: blocked.c server.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h zmalloc.h anet.h version.h util.h latency.h \
  sparkline.h counter.h
cluster.o: cluster.c server.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h zmalloc.h anet.h version.h util.h latency.h \
  sparkline.h cluster.h endianconv.h
config.o: config.c server.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  cluster.h counter.h
crc64.o: crc64.c
ddb.o: ddb.c server.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  cluster.h counter.h sha1.h endianconv.h rio.h
debug.o: debug.c server.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  sha1.h crc64.h counter.h bio.h
dict.o: dict.c fmacros.h dict.h zmalloc.h discntassert.h
discnt-cli.o: discnt-cli.c fmacros.h version.h ../deps/hiredis/hiredis.h \
  sds.h zmalloc.h ../deps/linenoise/linenoise.h help.h anet.h ae.h
server.o: server.c server.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  cluster.h counter.h bio.h asciilogo.h
endianconv.o: endianconv.c
counter.o: counter.c server.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  cluster.h counter.h sha1.h endianconv.h
latency.o: latency.c server.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h zmalloc.h anet.h version.h util.h latency.h \
  sparkline.h
lzf_c.o: lzf_c.c lzfP.h
lzf_d.o: lzf_d.c lzfP.h
memtest.o: memtest.c config.h
networking.o: networking.c server.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h zmalloc.h anet.h version.h util.h latency.h \
  sparkline.h
object.o: object.c server.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h sparkline.h
release.o: release.c release.h version.h crc64.h
rio.o: rio.c rio.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h sparkline.h \
  cluster.h counter.h sha1.h endianconv.h
sds.o: sds.c sds.h zmalloc.h
setproctitle.o: setproctitle.c
sha1.o: sha1.c sha1.h config.h
sparkline.o: sparkline.c server.h fmacros.h config.h ae.h sds.h dict.h \
  adlist.h zmalloc.h anet.h version.h util.h latency.h \
  sparkline.h
syncio.o: syncio.c server.h fmacros.h config.h ae.h sds.h dict.h adlist.h \
  zmalloc.h anet.h version.h util.h latency.h sparkline.h
util.o: util.c fmacros.h util.h sds.h sha1.h
zmalloc.o: zmalloc.c config.h zmalloc.h
